version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Mbot
    volumes:
      - ./:/Mbot
    environment:
      - PYTHONUNBUFFERED=1
    command: [ "sh", "-c", "python ./async_main.py && tail -f /dev/null" ]
    restart: always

